[project]
name = "breinbaas-slim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rob van Putten", email = "breinbaasnl@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "brodata>=0.1.6",
    "dotenv>=0.9.9",
    "fastapi>=0.115.6",
    "numpy>=2.4.3",
    "pydantic>=2.12.5",
    "python-multipart>=0.0.20",
    "requests>=2.32.5",
    "shapely>=2.1.2",
    "uvicorn>=0.34.0",
    "xmltodict>=1.0.4",
]

[build-system]
requires = ["uv_build>=0.10.9,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.0.2",
]
